# Generated by Django 3.0.4 on 2020-03-16 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('registerer_name', models.CharField(max_length=255)),
                ('registerer_email', models.EmailField(max_length=254)),
                ('registerer_role', models.CharField(max_length=100)),
                ('company_domain', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_first_name', models.CharField(max_length=100)),
                ('employee_last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('photo', models.ImageField(upload_to='')),
                ('google_id', models.CharField(max_length=255)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repository.Company')),
            ],
        ),
        migrations.CreateModel(
            name='ResearchProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rp_title', models.CharField(max_length=255)),
                ('rp_desc', models.TextField()),
                ('rp_time_start', models.DateField()),
                ('rp_time_end', models.DateField()),
                ('rp_created_at', models.DateField(verbose_name='created at')),
                ('rp_created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='repository.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_title', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ResearchRespondent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rr_name', models.CharField(max_length=255)),
                ('rr_phone', models.CharField(max_length=50)),
                ('rr_email', models.EmailField(max_length=254, null=True)),
                ('rr_occupation', models.CharField(max_length=255)),
                ('rr_gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=2)),
                ('research_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repository.ResearchProject')),
            ],
        ),
        migrations.CreateModel(
            name='ResearchQuestions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('research_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repository.ResearchProject')),
            ],
        ),
        migrations.CreateModel(
            name='ResearchAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField()),
                ('research_question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='repository.ResearchQuestions')),
                ('research_respondent', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='repository.ResearchRespondent')),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='repository.Role'),
        ),
    ]
