# Generated by Django 3.0.4 on 2020-04-15 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0006_auto_20200412_1438'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchproject',
            name='rp_of_company',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='repository.Company'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ProjectMembers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('research_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repository.ResearchProject')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repository.User')),
            ],
        ),
    ]
