# Generated by Django 3.0.4 on 2020-04-15 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0007_auto_20200415_2145'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repository.Company')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repository.User')),
            ],
        ),
    ]
