# Generated by Django 3.0.4 on 2020-04-15 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0009_auto_20200415_2335'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='registerer_role',
        ),
    ]
