# Generated by Django 3.0.4 on 2020-04-16 08:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0010_remove_company_registerer_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='company_registered_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='registered at'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='user_registered_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='registered at'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='user_updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
