# Generated by Django 3.0.4 on 2020-04-17 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0014_researchproject_rp_pic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='status_domain',
            new_name='status',
        ),
    ]
