# Generated by Django 3.0.4 on 2020-04-22 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0016_auto_20200422_1050'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProjectMembers',
            new_name='ProjectMember',
        ),
        migrations.RenameModel(
            old_name='ResearchQuestions',
            new_name='ResearchQuestion',
        ),
    ]
