# Generated by Django 3.0.4 on 2020-04-27 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0017_auto_20200422_1055'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchrespondent',
            name='rr_of_company',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='repository.Company'),
            preserve_default=False,
        ),
    ]
