# Generated by Django 3.0.4 on 2020-04-27 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0018_researchrespondent_rr_of_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='researchrespondent',
            name='research_project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='repository.ResearchProject'),
        ),
    ]
