# Generated by Django 3.0.4 on 2020-05-07 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0021_projectrespondent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='researchanswer',
            name='research_question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repository.ResearchQuestion'),
        ),
        migrations.AlterField(
            model_name='researchanswer',
            name='research_respondent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repository.ResearchRespondent'),
        ),
    ]
